### ISSUE TITLE
Unable to create a space

### ISSUE THREAD

**Issue by ozej8y** [espaces/espaces-deployment#20]
Hi David,

I'm unable to create this new space as part of the migration process.
ID: pervasive-and-persuasive-technology-for-healthcare
Text: Pervasive and Persuasive Technology for Healthcare

I have tried several times.
I found the following in the log that matches timestamp.
2014-02-13T08:44:15 ERROR collective.spaces.browser.createform Coud not create a Space
Traceback (most recent call last):
  File "/opt/espaces-platform/src/collective.spaces/src/collective/spaces/browser/createform.py", line 275, in handleApply
    new_space = utils._clone(self.context, template, space_id)
  File "/opt/espaces-platform/src/collective.spaces/src/collective/spaces/utils.py", line 16, in wrapper
    result = fn(_args, *_kwargs)
  File "/opt/espaces-platform/src/collective.spaces/src/collective/spaces/utils.py", line 39, in _clone
    return context.manage_clone(obj, clone_id)
  File "/opt/espaces-platform/eggs/Zope2-2.13.21-py2.7.egg/OFS/CopySupport.py", line 433, in manage_clone
    ob = ob._getCopy(self)
  File "/opt/espaces-platform/eggs/Zope2-2.13.21-py2.7.egg/OFS/CopySupport.py", line 586, in _getCopy
    self._p_jar.exportFile(self._p_oid,f)
  File "/opt/espaces-platform/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/ExportImport.py", line 66, in exportFile
    cp(blobdata, f)
  File "/opt/espaces-platform/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/utils.py", line 112, in cp
    write(data)
IOError: [Errno 28] No space left on device

**Comment by davidjb** [comment]
https://github.com/collective/collective.spaces/issues/3 -- that should fix it.
